class FBTABrowserConstant:
    DEBUG = 'DEBUG'
    DEBUG_SHOW_SOURCE = 'DEBUG_SHOW_SOURCE'
    SIGNAL_NORMAL_START = -2
    SIGNAL_NORMAL = -1

    DOING_TITLE_CHECK_ONLY = 'DOING_CHECK_ONLY_TITLE'
    DOING_CONTENT_CHECK_ONLY = 'DOING_CHECK_ONLY_CONTENT'

    STATUS_CONTENT_RELOAD = 5
    STATUS_CONTENT_RELOAD_ONCE = 6
    STATUS_LOGIN_AGAIN = 98
    STATUS_BROWSER_RESTART = 99
    STATUS_DO_NOTHING = -99

    STATUS_NORMAL = STATUS_DO_NOTHING

    FBSCOPE_PRIVATE = 0
    FBSCOPE_GLOBAL = 1

    NODE_MASTER = 'NODE_MASTER'
    NODE_SLAVE = 'NODE_SLAVE'
